.TH RADAR 1
.SH NAME
radar \- NWS Doppler radar on the command line 
.SH SYNOPSIS
.PP
.B radar ARGUMENT
.SH DESCRIPTION
.PP
.B radar 
is a tool for retrieving National Weather Service (NWS) Doppler radar imagery from the command line. It links to https://radar.weather.gov/lite/N0R/ and finds the animated .GIF file for a user-specified site. By default, it then opens this file with mpv(1), but this can be changed.
.SH COMMANDS
.TP
.B radar [ABC]
View the most current Doppler radar imagery from the site with the ICAO code ending in [ABC]. For instance, Memphis International Airport is KNQA; running "radar NQA" will open an animated .GIF of current precipitation conditions surrounding Memphis, TN. [ABC] is case-insensitive.
.TP
.B radar "City"
If the argument is a city name, radar will do its best to find the
corresponding city in the list of NEXRAD sites. While it's not strictly
necessary to enclose single word names in quotes (e.g. "Chicago"), it's
best practice to always do so. For city names containing spaces
(e.g. "Los Angeles"), quotes are mandatory. Cities with similar names may
match each other and give unwanted results. For instance, running "radar Jackson"
will show imagery for Jacksonville, FL. To avoid this, be specific and type
radar "Jackson, MS" or "Jacksonville, FL" instead. Lastly, cities are
case-sensitive.
.TP
.B radar --list, -l
Will print a list of every NEXRAD Doppler radar in the United States showing city, state, and ICAO code. You can pipe this into a pager or filter it with any command-line tool of your choice. The information is stored in /usr/local/radar/share/radars.csv. 
.TP
.B radar --search, -s [XYZ]
This is really a shortcut for piping the output of "radar list" into grep(1). [XYZ] can be any regular expression. For example, you can look up sites by US state if you know its postal code, e.g. you can list all sites in Texas by issuing the command "radar --search TX:". Or, you can filter for Air Force bases with "radar --search AFB." You can look up cities by name also, e.g. "radar --search 'Los Angeles'".
.TP
.B radar --url, -u [ABC]
Print the URL for the site "ABC" to stdout.
.TP
.B tle --help, -h 
Prints an abbreviated version of this man page to stdout. This is also the default behavior for when an incorrect or illegal argument is passed.
.TP
.SH EXAMPLES
.TP
.B radar BOX 
Display latest Doppler radar imagery from Boston, Massachusetts.
.TP
.B radar --search \(dqOK:\(rs|TX:\(dq
Will list all sites in Oklahoma and Texas.
.TP
.B $BROWSER $(radar --url "City")
Will open the imagery for "City" in your browser instead of mpv(1).
.TP
.SH AUTHOR
Written by Ray Patrick <ray@raypatrick.xyz> in 2020.
.SH LICENSE
GPLv3
.SH SEE ALSO
.B mpv(1), grep(1)
