.TH RADAR 1
.SH NAME
radar \- NWS Doppler radar on the command line 
.SH SYNOPSIS
.PP
.B radar [sitecode|city] [-l, --list] [-s, --search regex] [u, --url sitecode|city] [-h, --help]
.SH DESCRIPTION
.PP
.B radar 
is a tool for retrieving National Weather Service (NWS) Doppler radar imagery from the command line. It links to the "lite" version of the NWS RIDGE site and retrieves the animated .GIF file showing about the last 30 minutes of precipitation at the site you select. You can specify an ICAO code directly (such as KNQA for Memphis International Airport) or you can type a city name. If there's a WSR-88 site in that city,
.B radar
will find it and retrieve its imagery. Cities with spaces in their names should be encapsulated in quotes, for example "Los Angeles". 
.SH OPTIONS
.TP
.B [sitecode|city]
.B sitecode
can be any ICAO code, such as KOKX for New York City. Site codes are case-insensitive. Alternatively, you can specify a
.B city
and 
.B radar
will do its best to locate its imagery. Running
.B $ radar "New York"
gives identical results to
.B $ radar KNQA.
.TP
.B [-l, --list]
Will print a list of every NEXRAD Doppler radar in the United States, showing city, state, and ICAO code, to standard output. This information is stored in /usr/local/radar/share/radars.txt.
.TP
.B [-s, --search regex]
This is really a shortcut for
.B grep -w regex radars.txt.
Examples:
.B radar -s "TX:"
will list all the sites in Texas;
.B radar -s "AFB"
will list all the sites at US Air Force bases.
.TP
.B [-u, --url sitecode|city]
Just prints the generated URL to standard output instead of opening it with
.B mpv(1).
.TP
.B [-h, --help]
Prints an abbreviated set of usage instructions to standard output.
.SH FILES
.TP
.B /usr/local/radar/share/radars.txt 
Contains information on all NEXRAD sites in the United States. Each line has the form
.B City, ST: KABC,
where
.B ST
is the two-letter abbreviation for a US State and
.B KABC
is the ICAO code.
.SH BUGS
.TP
.B radar
is a POSIX shell script. On your system,
.B /bin/sh
must be a POSIX-compliant shell (or a link to one) for
.B radar
to work.
.SH LICENSE
.TP
GPLv3
.SH AUTHOR
.TP
Written by Ray Patrick <ray@raypatrick.xyz> in 2020.
.TP
https://raypatrick.xyz
.TP
ray@raypatrick.xyz
.SH LICENSE
.TP
GPLv3
.SH SEE ALSO
.TP
.B mpv(1)
